config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "items#index"
  
  resources :items do
    collection do
      get 'search', to: 'items#search'
    end
  end

  get "search_tag"=>"items#search_tag"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 1, name: '-' },
    { id: 2, name: '新品未開封' },
    { id: 3, name: '完品' },
    { id: 4, name: '美品' },
    { id: 5, name: '難有り' },
    { id: 6, name: 'ジャンク' },
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/item.rb
class Item < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings, dependent: :destroy

  has_many_attached :images

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :condition, class_name: 'Condition'
    belongs_to :rarity, class_name: 'Rarity'

  def self.search(search)
    if search.present?
      Item.joins(:tags).where(
        'items.name LIKE :search OR items.memo LIKE :search OR items.product LIKE :search OR tags.tag_name LIKE :search',
        search: "%#{search}%"
      ).distinct
    else
      Item.none
    end
  end
end

app/models/item_tag.rb
class ItemTag
  include ActiveModel::Model
  include ActiveModel::Attributes
  attr_accessor :name, 
                :condition_id, 
                :rarity_id, 
                :product, 
                :release, 
                :route, 
                :get_date, 
                :memo, 
                :images,
                :tag_name


  validates :name, presence: true

  def save
    tag_names = tag_name.split(',').map(&:strip)

    item = Item.create(
      name: name,
      condition_id: condition_id,
      rarity_id: rarity_id,
      product: product,
      release: release,
      route: route,
      get_date: get_date,
      memo: memo
    )

    tag_names.each do |tag_name|
      tag = Tag.where(tag_name: tag_name).first_or_initialize
      tag.save if tag.new_record?
      Tagging.create(item: item, tag: tag)
    end
  end
end

app/models/rarity.rb
class Rarity < ActiveHash::Base
  self.data = [
    { id: 1, name: '-' },
    { id: 2, name: '★☆☆☆☆' },
    { id: 3, name: '★★☆☆☆' },
    { id: 4, name: '★★★☆☆' },
    { id: 5, name: '★★★★☆' },
    { id: 6, name: '★★★★★' },
  ]
  end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, foreign_key: 'tag_id', dependent: :destroy
  has_many :items, through: :taggings

  before_destroy :destroy_orphaned_tag

  private

  def destroy_orphaned_tag
    puts "destroy_orphaned_tag method called"
    if items.empty?
      destroy
    end
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :item
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

    def index
      @items = Item.order(created_at: :desc).page(params[:page]).per(12) # アイテム一覧の取得
      @tag_list=Tag.all
    end
  
    def new
      @item_tag = ItemTag.new
    end
  
    def create
      @item_tag = ItemTag.new(item_tag_params)
      if @item_tag.valid?

        @item = Item.create(
          name: @item_tag.name,
          condition_id: @item_tag.condition_id,
          rarity_id: @item_tag.rarity_id,
          product: @item_tag.product,
          release: @item_tag.release,
          route: @item_tag.route,
          get_date: @item_tag.get_date,
          memo: @item_tag.memo
        )
        
        @item.images.attach(@item_tag.images)  # 画像をアタッチ

        tag_names = @item_tag.tag_name.split(',').map(&:strip)
        tag_names.each do |tag_name|
          tag = Tag.find_or_create_by(tag_name: tag_name)
          Tagging.create(item: @item, tag: tag)
        end
  
        redirect_to root_path
      else
        render :new
      end
    end
  
    def show
      @item = Item.find(params[:id])
    end

    def edit
      @item = Item.find(params[:id])
      @item_tag = ItemTag.new(
        name: @item.name,
        condition_id: @item.condition_id,
        rarity_id: @item.rarity_id,
        product: @item.product,
        release: @item.release,
        route: @item.route,
        get_date: @item.get_date,
        memo: @item.memo,
        tag_name: @item.tags.pluck(:tag_name).join(', ') #タグの間に, を入れて表示
      )
    end

    def update
      @item = Item.find(params[:id])
      @item_tag = ItemTag.new(item_tag_params)

        if @item_tag.valid?
          @item.tags.destroy_all
          if @item_tag.tag_name.present?
            tag_names = @item_tag.tag_name.split(',').map(&:strip).reject(&:blank?) #sprit(',')は,で区切って配列に変換する rejectは配列意外だとエラーになるので
                                                          #空でない（非空文字列である）タグ名の配列を取得
                                                          #blank? メソッドはオブジェクトが空かどうかを判定するメソッドで、空文字列や nil の場合に true を返します。
                                                          #reject メソッドは、指定された条件に一致する要素を取り除いた新しい配列を返します。
            tag_names.each do |tag_name| #配列の各要素に対して繰り返し処理
              tag = Tag.find_or_create_by(tag_name: tag_name) #Tag モデルから、与えられたタグ名 tag_name に対応するタグをデータベースから検索します。見つかればそのタグを、見つからなければ新しいタグを作成して返します。
              Tagging.create(item: @item, tag: tag) #Tagging モデルに新しいレコードを作成します。item カラムには @item インスタンスを、tag カラムには tag インスタンスを指定します。これにより、アイテムとタグの関連付けが行われます。
            end
          end
            if @item.update(
              name: @item_tag.name,
              condition_id: @item_tag.condition_id,
              rarity_id: @item_tag.rarity_id,
              product: @item_tag.product,
              release: @item_tag.release,
              route: @item_tag.route,
              get_date: @item_tag.get_date,
              memo: @item_tag.memo
            )
            redirect_to item_path(@item.id)
          else
            render :edit
          end
        else
          render :edit
        end
    end

    def destroy
      @item = Item.find(params[:id])
      @item.destroy
      redirect_to root_path
    end

    def search
      if params[:search].present?
        @search_results = Item.search(params[:search]).order(created_at: :desc).page(params[:page]).per(12)
        logger.debug "Search Results in Search Action: #{@search_results}"
      end
    end

    def search_tag
      # 検索結果画面でもタグ一覧表示
      @tag_list = Tag.all
      # 検索されたタグを受け取る
      @tag = Tag.find(params[:tag_id])
      # 検索されたタグに紐づく投稿を表示
      @items = @tag.items.order(created_at: :desc).page(params[:page]).per(12)
    end

    private
    def item_tag_params
      params.require(:item_tag).permit(:name, 
                                      :condition_id, 
                                      :rarity_id, 
                                      :product, 
                                      :release, 
                                      :route, 
                                      :get_date, 
                                      :memo, 
                                      :tag_name,
                                      {images: []})
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
  <div class="main__item-list">
    <div class="box__images box__images--list">
      <% if item.images.attached? %>
        <%= link_to item_path(item) do %>
          <%= image_tag item.images[0], class: "box__image" %>
        <% end %>
      <% end %>
    </div>

    <%= link_to item.name, item_path(item), class: :itemList__name %>
    
    <div class="item__tag-list">
      <!-- アイテムに関連するタグを取得 -->
      <% @tag_list = item.tags %>
      <!--タグリスト-->
      <% @tag_list.each do |list|%>
        <%=link_to list.tag_name,search_tag_path(tag_id: list.id) %>
        <%="(#{list.items.count})" %>
      <% end %>
    </div>

      <p>レア度：
        <% if item.rarity_id.present? %>
          <%= Rarity.find(item.rarity_id).name %>
        <% else %>
          -
        <% end %>
      </p>
  </div>

app/views/items/edit.html.erb
<div class="wrapper wrapper__form">
  <h2 class="page__title">
    <span class="material-symbols-rounded main__button--name">edit</span>
    <span class="main__button--name">編集する</span>
  </h2>

  <%= form_with(model: @item_tag, url: item_path(@item), local: true, method: :patch, id: 'item_form') do |f| %>
      <div class="field image-field">
        <div id="previews"></div>
        <div class="click-upload">
          <p>画像</p>
          <%= f.file_field :images, name: 'item_tag[images][]', data: {index: 0}, id: 'item_images' %>
        </div>
      </div>

      <div class="form__field">
        <%= f.label :name, "おなまえ" %>
        <%= f.text_field :name, placeholder: "アイテム名", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :tag_name, "タグ" %>
        <%= f.text_field :tag_name, placeholder: ",で区切って複数登録できます", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <p class="field_title">コンディション</p>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"form__input form__input--square"}) %>
      </div>
      <div class="form__field">
        <p class="field_title">レア度</p>
        <%= f.collection_select(:rarity_id, Rarity.all, :id, :name, {}, {class:"form__input form__input--square"}) %>
      </div>
      <div class="form__field">
        <%= f.label :product, "型番" %>
        <%= f.text_field :product, placeholder: "ウ-33", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :release, "発売時期" %>
        <%= f.text_field :release, placeholder: "1999年ごろ", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :route, "入手ルート" %>
        <%= f.text_field :route, placeholder: "リサイクルショップ", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :get_date, "入手時期" %>
        <%= f.text_field :get_date, placeholder: "2023年", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :nemo, "Memo" %>
        <%= f.text_area :memo, placeholder: "例:パッケージ傷あり", rows: "5", class:"form__input form__input--square" %>
      </div>

      <div class="button main__button">
        <%= f.submit "SAVE" %>
      
        <%= link_to item_path(@item.id), class:"" do %>
          <span class="material-symbols-rounded main__button--name">undo</span>
          <span class="main__button--name">もどる</span>
        <% end%>
      </div>
    <% end %>
</div>

app/views/items/index.html.erb
<div class="bg_image">
  <% if user_signed_in? %>
    <div class="bg_fff">
      <div class="wrapper">
        <h2 class="page__title">New arrival</h2>
            <div class="itemList__container">
              <% @items.each do |item| %>
                <%= render partial: "item", locals: { item: item } %>
              <% end %>
            </div>

            <%= paginate @items %>
      </div>
    </div>
  <% else %>
    <div class="top-page--not-login">
      <div class="top-page__box">
        <h2><%= image_tag "catch01.png", class: "top-page__catch top-page__catch--main" %></h2>
      </div>

      <div class="top-page__box">
        <div class="top-page-not-login__button--sign-up">
          <%= link_to new_user_registration_path do %>
            <span class="material-symbols-rounded main__button--name">person_add</span>
            <span class="main__button--name">新規登録</span>
          <% end %>
        </div>
      </div>

      <div class="top-page__box box__catch-sub">
        <%= image_tag "catch02.png", class: "top-page__catch--sub"  %>
        <%= image_tag "catch03.png", class: "top-page__catch--sub"  %>
        <%= image_tag "catch04.png", class: "top-page__catch--sub"  %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="wrapper wrapper__form">
  <h2 class="page__title">
    <span class="material-symbols-rounded main__button--name">add</span>
    <span class="main__button--name">登録する</span>
  </h2>

    <%= form_with(model: @item_tag, url: items_path, local: true, id: 'item_form') do |f| %>
      <div class="field image-field">
        <div id="previews"></div>
        <div class="click-upload">
          <p>画像</p>
          <%= f.file_field :images, name: 'item_tag[images][]', data: {index: 0}, id: 'item_images' %>
        </div>
      </div>

      <div class="form__field">
        <%= f.label :name, "おなまえ" %>
        <%= f.text_field :name, placeholder: "アイテム名", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :tag_name, "タグ" %>
        <%= f.text_field :tag_name, placeholder: ",で区切って複数登録できます", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <p class="field_title">コンディション</p>
        <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class:"form__input form__input--square"}) %>
      </div>
      <div class="form__field">
        <p class="field_title">レア度</p>
        <%= f.collection_select(:rarity_id, Rarity.all, :id, :name, {}, {class:"form__input form__input--square"}) %>
      </div>
      <div class="form__field">
        <%= f.label :product, "型番" %>
        <%= f.text_field :product, placeholder: "ウ-33", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :release, "発売時期" %>
        <%= f.text_field :release, placeholder: "1999年ごろ", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :route, "入手ルート" %>
        <%= f.text_field :route, placeholder: "リサイクルショップ", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :get_date, "入手時期" %>
        <%= f.text_field :get_date, placeholder: "2023年", class:"form__input form__input--round" %>
      </div>
      <div class="form__field">
        <%= f.label :nemo, "Memo" %>
        <%= f.text_area :memo, placeholder: "例:パッケージ傷あり", rows: "5", class:"form__input form__input--square" %>
      </div>

      <div class="button main__button">
        <%= f.submit "SAVE" %>
      </div>
    <% end %>
</div>

app/views/items/search.html.erb
<div class="bg_image">
  <div class="bg_fff">
    <div class="wrapper">
      <h2 class="page__title">検索結果</h2>
        <div class="itemList__container">
          <% if @search_results.present? %>
            <% @search_results.each do |item| %>
              <%= render partial: "item", locals: { item: item } %>
            <% end %>
            <%= paginate @search_results %>
          <% else %>
          <p>該当するアイテムはありません。</p>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/items/search_tag.html.erb
<div class="bg_image">
  <div class="bg_fff">
    <div class="wrapper">
      <h2 class="page__title">'<%= @tag.tag_name %>' 一覧</h2>
        <div class="itemList__container">
          <% if @tag.present? %>
            <% @items.each do |item| %>
              <%= render partial: "item", locals: { item: item } %>
            <% end %>
            <%= paginate @items %>
          <% else %>
          <p>該当するアイテムはありません。</p>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="wrapper">
  <h2 class="page__title"><%= @item.name %></h2>

  <div class="container">
    <div class="box__images--detail">
      <div class="box__images __image--main">
        <%= image_tag @item.images[0].variant(resize: '600x600'), class: "box__image", id: "mainimg" if @item.images.attached? && @item.images[0] %>
      </div>
      <div class="__image--thumbnails">
        <div class="__image--thumbnail">
          <%= image_tag @item.images[0], class: "box__image thumb" if @item.images.attached? && @item.images[0] %>
        </div>
        <div class="__image--thumbnail">
          <%= image_tag @item.images[1], class: "box__image thumb" if @item.images.attached? && @item.images[1] %>
        </div>
        <div class="__image--thumbnail">
          <%= image_tag @item.images[2], class: "box__image thumb" if @item.images.attached? && @item.images[2] %>
        </div>
        <div class="__image--thumbnail">
          <%= image_tag @item.images[3], class: "box__image thumb" if @item.images.attached? && @item.images[3] %>
        </div>
        <div class="__image--thumbnail">
          <%= image_tag @item.images[4], class: "box__image thumb" if @item.images.attached? && @item.images[4] %>
        </div>
      </div>
    </div>


        <div class="item__tag-list">
          <!-- アイテムに関連するタグを取得 -->
          <% @tag_list = @item.tags %>
          <!--タグリスト-->
          <% @tag_list.each do |list|%>
            <%=link_to list.tag_name,search_tag_path(tag_id: list.id) %>
            <%="(#{list.items.count})" %>
          <% end %>
        </div>

        <dl class="details__table">
          <dt class="table__header">なまえ</dt>
            <dd class="table__data">
              <%= @item.name %>
            </dd>
          <dt class="table__header">コンディション</dt>
            <dd class="table__data">
              <% if @item.condition_id.present? %>
                <%= Condition.find(@item.condition_id).name %>
              <% else %>
                -
              <% end %>
            </dd>
          
          <dt class="table__header">レア度</dt>
            <dd class="table__data">
              <% if @item.rarity_id.present? %>
                <%= Rarity.find(@item.rarity_id).name %>
              <% else %>
                -
              <% end %>
            </dd>
          
          <dt class="table__header">型番</dt>
            <dd class="table__data">
            <% if @item.product.present? %>
              <%= @item.product %>
            <% else %>
              -
            <% end %>
            </dd>
          
          <dt class="table__header">発売時期</dt>
            <dd class="table__data">
            <% if @item.release.present? %>
              <%= @item.release %>
            <% else %>
              -
            <% end %>
            </dd>
          
          <dt class="table__header">入手ルート</dt>
            <dd class="table__data">
              <% if @item.route.present? %>
                <%= @item.route %>
              <% else %>
                -
              <% end %>
            </dd>
          
          <dt class="table__header">入手時期</dt>
            <dd class="table__data">
              <% if @item.get_date.present? %>
                <%= @item.get_date %>
              <% else %>
                -
              <% end %>
            </dd>
          
          <dt class="table__header">memo</dt>
            <dd class="table__data">
              <% if @item.memo.present? %>
                <%= @item.memo %>
              <% end %>
            </dd>
        </dl>

      <div class="button main__button">
        <%= link_to edit_item_path(@item.id) do %>
          <span class="material-symbols-rounded main__button--name">edit</span>
          <span class="main__button--name">編集</span>
        <% end %>
        <%= link_to item_path(@item.id), data: { turbo_method: :delete } do %>
          <span class="material-symbols-rounded main__button--name">delete</span>
          <span class="main__button--name">削除</span>
        <% end%>
        <%= link_to root_path do %>
          <span class="material-symbols-rounded main__button--name">undo</span>
          <span class="main__button--name">もどる</span>
        <% end%>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magpie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300&family=Quicksand:wght@300&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/destyle.css@1.0.15/destyle.css"/>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header__grid gradient3color" id="pc">
      <h1 class="header__main-title">
        <%= link_to image_tag("logo.png", class:"header__logo--size"),root_path %>
      </h1>

      <div class="header__grid--right">
        <% if user_signed_in? %>
          <div class="header__menu">
            <%= link_to "/", class: "button header__button" do %>
              <span class="material-symbols-rounded main__button--name">apps</span>
              <span class="main__button--name">View collection
            <% end %>
          </div>

          <div class="header__menu">
            <%= form_with(url: search_items_path, local: true, method: :get, class: "header__form--search") do |form| %>
              <%= form.text_field :search, placeholder: "検索ワード", class: "header__search-input" %>
              <%= form.submit "Search", class: "button header__button" %>
            <% end %>
          </div>

          <div class="header__menu header__menu_logout">
              <h2 class="header__message header__menu--small">ようこそ、<%= current_user.nickname %>さん！</h2>
                <div class="button header__button">
                  <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "button__logout" do %>
                    <span class="material-symbols-rounded main__button--name header__menu--small">logout</span>
                    <span class="header__menu--name header__menu--small">Log out</span>
                  <% end %>
                </div>
            </div>

          </div>

        <% else %>
            <div class="header__menu header__menu_login">
              <%= link_to new_user_session_path, class: "button header__button" do %>
                <span class="material-symbols-rounded main__button--name">login</span>
                <span class="main__button--name">Log in</span>
              <% end %>
              <%= link_to new_user_registration_path, class: "button header__button" do %>
                <span class="material-symbols-rounded main__button--name">person_add</span>
                <span class="main__button--name">Sign up</span>
              <% end %>
            </div>
        <% end %>
      </div>
    </header><!--//pc-->
    <% unless current_page?(new_item_path) %>
      <%= link_to new_item_path, class: "__item-registration gradient2color" do %>
        <span class="material-symbols-rounded main__button--name">add</span>
        <span>登録する</span>
      <% end %>
    <% end %>

    <div id="sp">
      <% if user_signed_in? %>
        <header class="header__grid gradient3color">
          <h1 class="header__main-title">
            <%= link_to image_tag("logo.png", class:"header__logo--size"),root_path %>
          </h1>
          <div class="header__grid--right">
            <div class="header__hamburger">
              <span class="material-symbols-rounded menu_open">menu</span>
              <span class="material-symbols-rounded menu_close">close</span>
            </div>
          </div>
        </header>
        <ul class="sp_nav">
          <li>ようこそ、<%= current_user.nickname %>さん！</li>
          <li>
            <%= link_to "/", class: "header__menu--centering" do %>
              <span class="material-symbols-rounded main__button--name">apps</span>
              <span class="main__button--name">View collection</span>
            <% end %>
          </li>
          <li>
            <%= form_with(url: search_items_path, local: true, method: :get) do |form| %>
              <div class="header__menu--centering">
                <span class="material-symbols-rounded main__button--name">search</span>
                <span class="main__button--name">Search</span>
              </div>
                <%= form.text_field :search, placeholder: "検索ワード", class: "header__search-input" %>
              <p class="sp_nav_btn button header__button"><%= form.submit "検索" %></p>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "flex flex_center" do %>
              <span class="material-symbols-rounded main__button--name">logout</span>
              <span class="main__button--name">Log out</span>
            <% end %>
          </li>
        </ul>

      <% else %>
        <header class="header__grid gradient3color">
          <h1 class="header__main-title">
            <%= link_to image_tag("logo.png", class:"header__logo--size"),root_path %>
          </h1>

          <div class="header__menu--centering sign-in-or-login">
            <div class="header__menu header__menu--centering">
              <%= link_to new_user_session_path, class: "button header__button" do %>
                <span class="material-symbols-rounded main__button--name">login</span>
                <span class="main__button--name">Log in</span>
              <% end %>
              <%= link_to new_user_registration_path, class: "button header__button sp_hidden" do %>
                <span class="material-symbols-rounded main__button--name">person_add</span>
                <span class="main__button--name">Sign up</span>
              <% end %>
            </div>
          </div>

        </header>
      <% end %>
    </div><!--//sp-->

    <%= yield %>
    <footer class="footer gradient3color">
      <small>2023 marurun</small>
    </footer>
  </body>
</html>